### ISSUE TITLE
Video running too fast?

### ISSUE THREAD

**Issue by MicrowaveableTupperware** [MobyGamer/XDC#5]
Per the title, it seems the video always runs too fast. I have an ESS ES488 SB clone, which isn’t supported, so it defaults to using quiet mode. Any advice?

**Comment by MobyGamer** [comment]
Is it running too fast with videos I've provided, or videos you've made?  Have you specifically used the /q switch and has it helped?

Also, the ESS ES488 was supposed to be Sound Blaster compatible; have you set a BLASTER variable and tested it with other sound blaster-only software?

**Comment by MicrowaveableTupperware** [comment]
Apologies, I’ll give more detail. The videos you’ve provided run fine, it’s videos that I’ve created that run too fast, and that’s with quiet mode enabled. I’ve set the blaster parameters to their defaults (220,7,1,3), yet the program states “Fatal Error: Couldn’t Initialize Sound Blaster” and fails to run when the card is installed. I assume it’s the card, as it doesn’t play music in some games/software that has it. (Doom, Protracker II)

**Comment by MobyGamer** [comment]
In quiet mode, the program uses the system timer to deliver the same framerate as the soundcard's IRQ would have, so if the videos are playing too fast, you may have authored them incorrectly.  I would double-check any math or numbers in the input script, and also see what xdcplay prints out to see if the finished file matches what you think it should.

I would try to get your card working, as it's much more fun with sound (Doom as well :-)  Doom working with digital audio should be your first troubleshooting step, since that card is supposed to work as a sound blaster clone.  Maybe you need UNISOUND to init the card?  https://www.vogons.org/viewtopic.php?t=72553 has more info.

**Comment by MicrowaveableTupperware** [comment]
I’ll try that again later. As for the machine, it’s a Compaq Portable, and I didn’t think UNISOUND has support for the ES488. I opened a post on the vcfed about potential drivers and whatnot.

https://forum.vcfed.org/index.php?threads/help-identifying-a-sound-card.1246927/

**Comment by MobyGamer** [comment]
Might want to try asking VOGONS for help, they're more the "how can I drive this soundcard" crowd.

**Comment by MicrowaveableTupperware** [comment]
I’m back! Fixed the soundcard, and everything works perfectly. Might have just been issues with the soundcard.

**Comment by MobyGamer** [comment]
Thanks for the confirmation, and glad you got it working!
